updated host input loop for switch case

diff --git a/update-thingz b/update-thingz
--- a/update-thingz
+++ b/update-thingz
@@ -126,23 +126,24 @@ then
     ## compression
     tar -czPf ${ZIP} ${TMP}
 
+    ## inputs
     case "$1" in
 	-s|--servers) TARGET=${MACHINES} ;;
 	-d|--desktops) TARGET=${DESKTOPS} ;;
 	-l|--list) TARGET=`echo $@ |cut -d' ' -f2-` ;;
-	-H|--hosts) if [ $# == 4 ]
-then
-    if [ "${3}" == "-C" -o "${3}" == "--config" ] 
-    then
-	echo ${4}
+	-H|--hosts) if [ $# -eq 4 ]; then
+    if [ "${3}" == "-C" -o "${3}" == "--config" ]; then
+	if [ -r ${2} -a -r ${4} ]; then
+	    echo "good files"
+	else
+	    echo "cannot open/read files"
+	    exit 1
+	fi
     else
 	echo "try -C instead of ${3}"
 	exit 1
-    fi
-else
-    echo "incorrect number of arguments"
-    exit 1
-    fi ;;
+    fi 
+fi ;;
 	*) echo "unknown option"
 	    exit 1;;
     esac
@@ -165,10 +166,10 @@ else
 		echo -n "."
 		;;
     	    *) ${RSYNC_OPTS} ${ZIP} ${host}:/tmp 
-	    echo -n "."
-    	    ${SSHELL} "${KEYCHECK}" ${host} "${UNTAR} && ${MOVE} && ${CLEAN}"
-	    echo -n "."
-    	    ;;
+		echo -n "."
+    		${SSHELL} "${KEYCHECK}" ${host} "${UNTAR} && ${MOVE} && ${CLEAN}"
+		echo -n "."
+    		;;
     	esac
     done
 
@@ -179,7 +180,7 @@ else
     TIME="$(expr ${FIN} - ${START})"
     echo -e "\n"`date -u -d @${TIME} +"%M:%S"`" elapsed"
     echo "crescent fresh!"
-else
+    else
     echo "do you even keys, br0?"
     exit 1
-fi
+    fi
